models:
  - type: main
    engine: nvidia_ai_endpoints
    model: meta/llama-3.3-70b-instruct

rails:
  config:
    injection_detection:
      injections:
        - code
        - sqli
        - template
        - xss
      action: reject

  output:
    streaming:
      enabled: True
      chunk_size: 200
      context_size: 50

streaming: True
